services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minigpt-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: minigpt-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend